# Generated by Django 2.2.5 on 2019-09-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_auto_20190916_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
